### ISSUE TITLE
UTF-8 character in comment cannot be commited

### ISSUE THREAD

**Issue by tloist** [innoq/iBlog#196] opened 2015-03-03 22:40 UTC
I just tried to commit a comment which contained the UTF-8 [Warning sign](http://www.fileformat.info/info/unicode/char/26a0/index.htm): ⚠

That didn't work and showed me an error message "We're sorry, but something went wrong."
Interesstingly the preview **did** work and showed me the comment correctly - but commiting it afterwards didn't work.

**Comment by FND** [comment] 2015-03-04 05:52
dupe of #57 / #118

however, the preview aspect is interesting - though the database config looks fine; @mjansing, any ideas?

**Comment by mjansing** [comment] 2015-03-04 08:19
I'll take a look at it.

**Comment by tloist** [comment] 2015-03-04 09:02
*arghs* I searched for UTF-8 not for Unicode, sorry for the duplicate.

**Comment by aknrdureegaesr** [comment] 2015-03-04 09:23
FWIW: If I remember correctly, the preview functionality had been added to iBlog by some UTF-8 aficionado.

**Comment by mjansing** [comment] 2015-03-05 09:46
I fix it in 6a552d64d5c65d500d085a050b0cee218b274d49. Our database was encoded with `latin1` and a `latin1_swedish_ci`-collation. I migrated the database to utf8/utf8_general_ci. Reopen if there a any issues.

**Closed by mjansing** 2015-03-05 09:46 UTC
